version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  discovery-service:
    image: discovery-service-img
    container_name: discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - gateway

  gateway:
    image: gateway-service-img
    container_name: gateway
    ports:
      - "8222:8222"
    depends_on:
      - config-server

  config-server:
    image: config-server-img
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - broker


#
#  inventory-service:
#    image: inventory-service-img
#    container_name: inventory-service
#    ports:
#      - "8084:8084"
#    depends_on:
#      - discovery-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_inventory:3306/inventories
#      SPRING_DATASOURCE_USERNAME: username
#      SPRING_DATASOURCE_PASSWORD: password
#
#  order-service:
#    image: order-service-img
#    container_name: order-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - discovery-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_order:3306/orders
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: password
#
#  product-service:
#    image: product-service-img
#    container_name: product-service
#    ports:
#      - "8083:8083"
#    depends_on:
#      - discovery-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_product:3306/products
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: password
#
#  user-service:
#    image: user-service-img
#    container_name: user-service
#    ports:
#      - "8081:8081"
#    depends_on:
#      - discovery-service
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_user:3306/users
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: password



