server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-system
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE

application:
  name: USER-SERVICE
  security:
    jwt:
      Secret_key: mysecretkey

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false







