server:
  port: 8084
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: inventory-service
