server:
  port: 8084
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/inventories
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#Actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus